version: '3.8'

services:
  bot:
    image: node:18
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_LOG_ID=${CHANNEL_LOG_ID}
    volumes:
      - bot_data:/app/data
    working_dir: /app
    command: sh -c "npm install && node index.js"

volumes:
  bot_data:
