version: '3.8'

services:
  scalex-bot-discord:
    build: .
    container_name: scalex-bot-discord
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    working_dir: /app
